### ISSUE TITLE
Ctrl+D (EOF) without typing a command causes Segmentation fault

### ISSUE THREAD

**Issue by ajmaln** [tmly115/SimpleShell#8]
I think the desired outcome on pressing Ctrl+D or encountering EOF when no command is written would be just to gracefully terminate the shell.

**Comment by ajmaln** [comment]
Just saw this commit and I think segmentation fault is fixed by this one. https://github.com/tmly115/SimpleShell/commit/13a76657483dad3ffb07cd2f79a902bafacaef4e

Still I would suggest closing shell on EOF

**Comment by tmly115** [comment]
Yeah I've just fixed the segmentation fault. And yeah thinking about it it makes sense to exit the shell on parsing EOF I didn't even realize that was a thing in bash until now thanks!
